#### Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [28]:
import numpy as np

array = np.array ([1,2,4,7,9])
print (array)
if array.ndim > 1:
    print("Error")
else: 
    print("El numero mayor es: ",array.max())
    sumArray= 0
    media = 0

    for i in array:
        sumArray= sumArray + i
    
    media = sumArray/ len(array)

    print("La media es: ",media)

[1 2 4 7 9]
El numero mayor es:  9
La media es:  4.6


#### Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [12]:
array2= np.random.randint(0,100, size=(5,5))
print(array2)

[[71 41 62 44 65]
 [68 87 12  0 13]
 [66 82 58 94 37]
 [43 85  7 53  2]
 [78 11 58  9 58]]


#### Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [7]:
import numpy as np
array2d= np.random.randint(1,20, size=(3,5))
print(array2d)

print("La dimension del array es: ",array2d.ndim)
print("La forma del array es: ",array2d.shape)

sumaColumnas = np.sum(array2d, axis=0)
sumaFilas = np.sum(array2d, axis=1)
print (sumaColumnas)
print (sumaFilas)

[[ 7  8  7  4 15]
 [16  6  4  2 12]
 [15  3 12  1 17]]
La dimension del array es:  2
La forma del array es:  (3, 5)
[38 17 23  7 44]
[41 40 48]


#### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [63]:
x = np.array ([3,6,7,13])
y = np.array ([4,8,3,13])

coe = np.corrcoef(x, y)

print (coe)

print ("-----------")

def coefficienteC (x, y): 
    mediaX = sum(x)/len(x)
    mediaY = sum(y)/len(y)

    cov = sum((a - mediaX) * (b - mediaY) for (a,b) in zip(x,y)) / len(x)

    stDevX = (sum((a - mediaX)**2 for a in x)/len(x))**0.5
    stDevY = (sum((b - mediaY)**2 for b in y)/len(y))**0.5

    result = round(cov/(stDevX*stDevY),3)

    return result

print (coefficienteC (x, y))

[[1.         0.82184663]
 [0.82184663 1.        ]]
-----------
0.822


The Pearson correlation coefficient measures the linear association between variables. Its value can be interpreted like so:

+1 - Complete positive correlation
+0.8 - Strong positive correlation
+0.6 - Moderate positive correlation
0 - no correlation whatsoever
-0.6 - Moderate negative correlation
-0.8 - Strong negative correlation
-1 - Complete negative correlation

En el caso analizado el coeficiente de correlacion nos proporciona un resultado de correlación positiva en la que las dos variable se mueven en una dirección cresciente y tienen un coefficiente de correlación positivo FUERTE, esto quere decir que las dos variables tienen un alto grado de influencia reciproco.